CREATE TABLE CUSTOMERS (
CUSTOMERID NUMBER PRIMARY KEY,
AGE NUMBER,
BALANCE NUMBER,
ISVIP VARCHAR2(10)
);

CREATE TABLE LOANS (
LOANID NUMBER PRIMARY KEY,
CUSTOMERID NUMBER,
INTERESTRATE NUMBER,
DUEDATE DATE
);