-- Customers Table

CREATE TABLE Customers_E5
(
    CustomerID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(50),
    City VARCHAR2(30),
    LastModified DATE
);

-- Accounts Table

CREATE TABLE Accounts_E5
(
    AccountID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    Balance NUMBER(10,2)
);

-- Transactions Table

CREATE TABLE Transactions_E5
(
    TransactionID NUMBER PRIMARY KEY,
    AccountID NUMBER,
    TransactionType VARCHAR2(20),
    Amount NUMBER(10,2)
);

-- Audit Log Table

CREATE TABLE AuditLog_E5
(
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    LogDate DATE
);